version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"  # Cambia si usas un servidor web diferente
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: Lara_testing
      DB_USERNAME: root
      DB_PASSWORD: secret

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: Lara_testing
    ports:
      - "3306:3306"  # Puerto MySQL
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
